# -*- coding: utf-8 -*-
"""Lojas_Bermudas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nOvr5bRCFAlr5HqlaDlFz3ICXB8SKFRh

**Desafio:**

Certa empresa de Bermudas possui 5 lojas e está querendo aumentar as vendas. Desta forma, fazendo uso da base de vendas, o que ela deve fazer para alcançar tal objetivo?
"""

import pandas as pd

bermudas = pd.read_excel('/content/drive/MyDrive/data_scientist/VendasBermudas.xlsx')
display(bermudas.head())

display(bermudas.shape)
display(bermudas.info())
display(bermudas.describe())

# De acordo com esta base de dados, qual foi o faturamento total da empresa?
faturamento_total = bermudas['Valor Final'].sum()
display(faturamento_total)

# De acordo com esta base de dados, qual foi o faturamento por loja?
# Neste caso, será calculado a soma do faturamento em cada loja (groupby)
faturamento_Loja = bermudas[['ID Loja', 'Valor Final']].groupby('ID Loja').sum()
display(faturamento_Loja)

# De acordo com esta base de dados, qual foi o faturamento por produto?
faturamento_produto = bermudas[['ID Loja', 'Produto', 'Valor Final']].groupby(['ID Loja', 'Produto']).sum()
display(faturamento_produto)



"""Ao analisar os dados da base de vendas, notamos que a loja situada no Iguatemi Campinas possui um faturamente bem acima das demais, com um valor final de 41.720,00 reais. Dando uma ênfase maior a esta loja, percebemos que um dos produtos está se sobressaindo em relação aos demais. Este produto é a bermuda lisa com faturamento final de 36.581,00 reais.
Provavelmente, este é um produto novo lançado apenas nesta loja, visto que nas outras quatro este tipo de bermuda não é comercializada. Visto isso, a solução mais fácil para esta empresa aumentar as vendas, é: testar esta bermuda lisa nas outras quatro lojas, pois este produto esta sendo responsável por uma porcentagem alta do faturamento.
"""